Landing page
CSUI2021/ka-frontend pull request #30
Opened 2021-11-09 06:38 UTC by edutjie

2021-11-09 22:41 UTC, codewithdjaeger approved these changes

2021-11-09 22:50 UTC, codewithdjaeger requested changes
- Please change this file name, `app/components/landing-page/OurStories/utils/[contents].tsx`, because the use of `[]` is only for dynamic file naming

2021-11-12 11:42 UTC, codewithdjaeger requested changes
Next Time, Please do not push commented code without any information provided

2021-11-12 11:42 UTC, codewithdjaeger commented on app/components/landing-page/OurStories/index.tsx
> +					</Link> */}
Will it be used again?

2021-11-12 11:42 UTC, codewithdjaeger commented on app/components/landing-page/OurStories/interfaces/StoryProps.interface.tsx
> +export interface StoryProps {
Please change the file name format into `[component].interface.tsx` and the class name into [Component]Interface

2021-11-12 11:42 UTC, codewithdjaeger commented on app/components/landing-page/Messages/index.tsx
> +					{/* <p className='max-w-xs text-center 2sm:max-w-4xl 2sm:text-left'> */}
What is this comment for?

2021-11-12 12:13 UTC, edutjie commented on app/components/landing-page/Messages/index.tsx
> +					{/* <p className='max-w-xs text-center 2sm:max-w-4xl 2sm:text-left'> */}
ohh itu code yang lama lupa apus 🤦‍♂️

2021-11-12 12:52 UTC, codewithdjaeger approved these changes

2021-11-12 12:53 UTC, merged