Bee
CSUI2021/ka-frontend pull request #37
Opened 2021-11-13 09:56 UTC by al-ayubi2020

2021-11-13 11:51 UTC, codewithdjaeger requested changes

2021-11-13 11:51 UTC, codewithdjaeger commented on pages/components/SIG/DesktopSIG.tsx
> +						</div>
this could be refactored into separated components and you could do a mapping instead of write it repeatedly

2021-11-13 11:51 UTC, codewithdjaeger commented on pages/components/SIG/MobileSIG.tsx
> +	transform: rotate(166.08deg);
refactored it into standalone styled component

2021-11-13 11:51 UTC, codewithdjaeger commented on pages/components/SIG/MobileSIG.tsx
> +			<GradientBackgroundRed />
remove this

2021-11-13 11:51 UTC, codewithdjaeger commented on pages/components/SIG/MobileSIG.tsx
> +		</div>
I think you could refactored it

2021-11-14 00:04 UTC, codewithdjaeger requested changes

2021-11-14 00:04 UTC, codewithdjaeger commented on pages/components/SIG/DekstopTicket.tsx
> +export default DesktopTicket
Put it in app folder

2021-11-14 00:04 UTC, codewithdjaeger commented on pages/components/SIG/DekstopTicket.tsx
> +export default DesktopTicket
Put it in app folder

2021-11-14 00:04 UTC, codewithdjaeger commented on pages/components/SIG/DesktopSIG.tsx
> +export default DesktopSIG
Put it in app folder

2021-11-14 00:04 UTC, codewithdjaeger commented on pages/components/SIG/MobileTicket.tsx
> +export default MobileTicket
Put it in app folder

2021-11-14 23:19 UTC, DJaegerScript requested changes

2021-11-14 23:19 UTC, DJaegerScript commented on pages/components/SIG/MobileSIG.tsx
> +					<MobileTicket />
You could do mapping on this part

2021-11-15 22:52 UTC, DJaegerScript requested changes

2021-11-15 22:52 UTC, DJaegerScript commented on app/components/sig/interfaces/Sig.ts
> +interface Sig {
chnage the name inton sigInterface

2021-11-15 22:52 UTC, DJaegerScript commented on pages/passions/index.tsx
>  			<GradientBackgroundBlue />
Delete this

2021-11-17 09:32 UTC, closed without merging